### ISSUE TITLE
forgot to apply torch.exp to mu?

### ISSUE THREAD

**Issue by xuefei-wang** [camlab-bioml/astir#12]
https://github.com/camlab-bioml/astir/blob/b9984ffd28533d169eb389919cce0ece67a19158/astir/models/celltype.py#L181

Hi, I noticed that here mu is still in the log scale. Did you forget to apply exp operation to it? Thanks!

**Comment by kieranrcampbell** [comment]
The exponentiation happens at

https://github.com/camlab-bioml/astir/blob/b9984ffd28533d169eb389919cce0ece67a19158/astir/models/celltype.py#L196

**Comment by xuefei-wang** [comment]
Yeah, sorry, you are correct. Thanks for the clarification!

Can I ask why do you take exp after adding the two mean? Do you assume: `final_expression = base_expression * overexpression`?

**Comment by kieranrcampbell** [comment]
It's inspired by log link functions in generalized linear models, see e.g. https://en.wikipedia.org/wiki/Generalized_linear_model#Link_function

It ensures both the modelled means are always positive (since the expression data is positive) and yes the ultimate effect is the marker will be a multiplicative effect on the expression of a protein which has worked well in practice in our hands.

**Comment by xuefei-wang** [comment]
Thanks!
