### ISSUE TITLE
Negative expression

### ISSUE THREAD

**Issue by vytnav** [camlab-bioml/astir#17]
Is there a possibility to specify the negatively expressed (absent) marker for cell phenotyping? If no, maybe you have some ideas on how the expression data could be inverted to make a synthetic negative expression channel?

**Comment by kieranrcampbell** [comment]
This is a really interesting question that we've discussed several times. The 'negative marker' idea was hard for the datasets we looked at since there was always some non-zero background expression, so automatically deciding a threshold for something to be called non-expressed was hard.

One workaround is to add the channel as a marker for all other cell types, ie if you want a CD44- population, add CD44 to all other channels, though this isn't ideal. 

I like the synthetic channel idea though - if the expression values for the relevant channel are `x` that range from 0 to `M` (where `M = max(x)`) then you could create a new channel `x' = M - x` (that is essentially the inverse expression) and declare that as a marker. Let me know how you get on!
