### ISSUE TITLE
Installation failed on python 3.6

### ISSUE THREAD

**Issue by ngreenwald** [camlab-bioml/astir#4]
When building Astir, I'm running into the following issue on 3.6. I see in your documentation that 3.7 is suggested, but it also says that Astir works for 3.X. Is this the case, or is 3.7 or greater required?

(env) path_to_astir/astir$ pip3 install astir
Collecting astir
  Downloading https://files.pythonhosted.org/packages/f9/ad/f26a76ad385e13be8e5369af87bec3c64743de7e9830a6ef9d71024cecec/astir-0.1.0-py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 3.7MB/s 
Collecting torch (from astir)
  Using cached https://files.pythonhosted.org/packages/b6/01/fffb29c3892d80801bc6400e07c90b8fa6cd5f3db5ce9d7ca8068e14e0b2/torch-1.7.1-cp36-none-macosx_10_9_x86_64.whl
Collecting sklearn (from astir)
  Using cached https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Collecting h5py (from astir)
  Using cached https://files.pythonhosted.org/packages/34/8b/24796b39111b4a235051003986b1c6d43e8b9699ec5936b642231c101c40/h5py-3.1.0-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting sphinx-rtd-theme (from astir)
  Downloading https://files.pythonhosted.org/packages/76/81/d5af3a50a45ee4311ac2dac5b599d69f68388401c7a4ca902e0e450a9f94/sphinx_rtd_theme-0.5.1-py2.py3-none-any.whl (2.8MB)
    100% |████████████████████████████████| 2.8MB 594kB/s 
Collecting tqdm (from astir)
  Using cached https://files.pythonhosted.org/packages/d9/13/f3f815bb73804a8af9cfbb6f084821c037109108885f46131045e8cf044e/tqdm-4.57.0-py2.py3-none-any.whl
Collecting autodocsumm (from astir)
  Downloading https://files.pythonhosted.org/packages/d4/be/f43ec3bea9d525addc1345a52c7d077e95d90a15010a023921923ba7fb24/autodocsumm-0.2.2.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 9.5MB/s 
Collecting nbformat (from astir)
  Using cached https://files.pythonhosted.org/packages/13/1d/59cbc5a6b627ba3b4c0ec5ccc82a9002e58b324e2620a4929b81f1f8d309/nbformat-5.1.2-py3-none-any.whl
Collecting pyyaml (from astir)
  Using cached https://files.pythonhosted.org/packages/ef/e9/d62912119552b157ed66dc8297ae6ac08629d7d5c497d4faa26b0c3a4efe/PyYAML-5.4.1-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting anndata (from astir)
  Using cached https://files.pythonhosted.org/packages/81/b1/743cc79f89d9db6dccbfb7e6000795acb218a6c6320b7a2337cad99bd047/anndata-0.7.5-py3-none-any.whl
Collecting nbconvert (from astir)
  Using cached https://files.pythonhosted.org/packages/13/2f/acbe7006548f3914456ee47f97a2033b1b2f3daf921b12ac94105d87c163/nbconvert-6.0.7-py3-none-any.whl
Collecting argparse (from astir)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting fastcluster (from astir)
  Using cached https://files.pythonhosted.org/packages/56/5c/e227399348a5157698bd43962be10d9abe6be5d2236cd25d9710d0522982/fastcluster-1.1.28.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sg/3vdk73p96sq5rdljs50kqmn00000gp/T/pip-build-z9ehuqts/fastcluster/setup.py", line 12, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

**Comment by kieranrcampbell** [comment]
I can't seem to reproduce this error. In particular, if I create a new conda env to make sure I have your python version:

```bash
conda create -n testastir python=3.6
```
activate it:
```bash
conda activate testastir
```
Install astir via pip:
```bash
pip3 install astir
```
I can then import astir, ie
```bash
python -c "import astir"
```
runs without error. Can you share more details of your system? Thanks

**Comment by ngreenwald** [comment]
Hi Kieran, 
Thanks for the quick response. I was using virtualenv, not conda, to set up my environment. It appears there was something weird going on there, it now works fine. 

However, I'm not able to install the dev version, even with the conda env. 

```
conda create -n testastir python=3.6
conda activate testastir
pip install -e .
ERROR: Package 'astir' requires a different Python: 3.6.12 not in '<4.0.0,>=3.7.2'
```

After switching to 3.7.2, I get the following error:
```
conda create -n testastir python=3.7.2
conda activate testastir
pip install -e .
```

Obtaining file://long_path/astir
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pydantic<2.0.0,>=1.5.1
  Using cached pydantic-1.7.3-cp37-cp37m-macosx_10_9_x86_64.whl (2.3 MB)
Installing collected packages: pydantic, astir
  Running setup.py develop for astir
    ERROR: Command errored out with exit status 1:
     command: /Users/noahgreenwald/anaconda3/envs/testastir/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/long_path/astir/setup.py'"'"'; __file__='"'"'/long_path/astir/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /long_path/astir/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

However, the conda env does appear to have setuptools installed, since the following doesn't produce an error. 

```python -c 'import setuptools```

Thanks,
Noah

**Comment by kieranrcampbell** [comment]
Ok, I reproduced this. It seems isolated to a [known bug](https://github.com/pypa/setuptools/issues/2353) in the later versions of pip caused by having a `pyproject.toml` in the package. I've removed this for now and the package now builds fine. Please let me know if this fixes it on your end (new version pushed to github). Thanks

**Comment by ngreenwald** [comment]
Yup, that did the trick, thanks!

**Comment by joaoufrj** [comment]
Hello @kieranrcampbell , I think I am going through a similar issue. The problem is when I try to install Astir, the installation fails when trying to build wheel for fastcluster. The following happens:
Building wheels for collected packages: fastcluster
  Building wheel for fastcluster (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/joaoluizsfilho/env/python/bin/python3 /Users/joaoluizsfilho/env/python/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/rl/ypn8k8pn6sn46890b2gh46040000gn/T/tmpbrpnzrr7
       cwd: /private/var/folders/rl/ypn8k8pn6sn46890b2gh46040000gn/T/pip-install-v1rg1b__/fastcluster_1a9f497dfd5b4427b4a3a3054c68834e
  Complete output (107 lines):
  Fastcluster version: 1.2.4
  Python version: 3.8.5 (default, Sep  4 2020, 02:22:02)
  [Clang 10.0.0 ]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  copying fastcluster.py -> build/lib.macosx-10.9-x86_64-3.8
  running build_ext
  building '_fastcluster' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/src
  x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/joaoluizsfilho/miniconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/joaoluizsfilho/miniconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/joaoluizsfilho/miniconda3/include -I/private/var/folders/rl/ypn8k8pn6sn46890b2gh46040000gn/T/pip-build-env-3g1l4f5a/overlay/lib/python3.8/site-packages/numpy/core/include -I/Users/joaoluizsfilho/env/python/include -I/Users/joaoluizsfilho/miniconda3/include/python3.8 -c src/fastcluster_python.cpp -o build/temp.macosx-10.9-x86_64-3.8/src/fastcluster_python.o
  clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
  In file included from src/fastcluster_python.cpp:28:
  /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:14:2: error: "Something's broken.  UCHAR_MAX should be defined in limits.h."
  #error "Something's broken.  UCHAR_MAX should be defined in limits.h."
   ^
  /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:18:2: error: "Python's source code assumes C's unsigned char is an 8-bit type."
  #error "Python's source code assumes C's unsigned char is an 8-bit type."
   ^
  /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:27:5: error: "Python.h requires that stdio.h define NULL."
  #   error "Python.h requires that stdio.h define NULL."
      ^
  In file included from src/fastcluster_python.cpp:28:
  In file included from /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:30:
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:73:64: error: use of undeclared identifier 'strchr'
  char* __libcpp_strchr(const char* __s, int __c) {return (char*)strchr(__s, __c);}
                                                                 ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:80:75: error: use of undeclared identifier 'strpbrk'
  char* __libcpp_strpbrk(const char* __s1, const char* __s2) {return (char*)strpbrk(__s1, __s2);}
                                                                            ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:87:65: error: use of undeclared identifier 'strrchr'; did you mean 'strchr'?
  char* __libcpp_strrchr(const char* __s, int __c) {return (char*)strrchr(__s, __c);}
                                                                  ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:75:13: note: 'strchr' declared here
  const char* strchr(const char* __s, int __c) {return __libcpp_strchr(__s, __c);}
              ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:94:49: error: unknown type name 'size_t'
  void* __libcpp_memchr(const void* __s, int __c, size_t __n) {return (void*)memchr(__s, __c, __n);}
                                                  ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:96:46: error: unknown type name 'size_t'
  const void* memchr(const void* __s, int __c, size_t __n) {return __libcpp_memchr(__s, __c, __n);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:98:46: error: unknown type name 'size_t'
        void* memchr(      void* __s, int __c, size_t __n) {return __libcpp_memchr(__s, __c, __n);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:101:74: error: use of undeclared identifier 'strstr'; did you mean 'strchr'?
  char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                           ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:77:13: note: 'strchr' declared here
        char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
              ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:101:74: error: no matching function for call to 'strchr'
  char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                           ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:77:13: note: candidate disabled: <no message provided>
        char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
              ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:101:81: error: cannot initialize a parameter of type 'char *' with an lvalue of type 'const char *'
  char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                                  ^~~~
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:77:32: note: passing argument to parameter '__s' here
        char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
                                 ^
  In file included from src/fastcluster_python.cpp:28:
  In file included from /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:34:
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/stdlib.h:142:34: error: unknown type name 'ldiv_t'
  inline _LIBCPP_INLINE_VISIBILITY ldiv_t div(long __x, long __y) _NOEXCEPT {
                                   ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/stdlib.h:143:12: error: no member named 'ldiv' in the global namespace
    return ::ldiv(__x, __y);
           ~~^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/stdlib.h:146:34: error: unknown type name 'lldiv_t'
  inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x,
                                   ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/stdlib.h:148:12: error: no member named 'lldiv' in the global namespace
    return ::lldiv(__x, __y);
           ~~^
  In file included from src/fastcluster_python.cpp:28:
  In file included from /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:63:
  In file included from /Users/joaoluizsfilho/miniconda3/include/python3.8/pyport.h:212:
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:771:93: error: no member named 'acosf' in the global namespace; did you mean 'acos'?
  inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                                                                            ~~^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:771:46: note: 'acos' declared here
  inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:772:93: error: no member named 'acosl' in the global namespace; did you mean 'acos'?
  inline _LIBCPP_INLINE_VISIBILITY long double acos(long double __lcpp_x) _NOEXCEPT {return ::acosl(__lcpp_x);}
                                                                                            ~~^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:771:46: note: 'acos' declared here
  inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:778:38: error: call to 'acos' is ambiguous
  acos(_A1 __lcpp_x) _NOEXCEPT {return ::acos((double)__lcpp_x);}
                                       ^~~~~~
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:771:46: note: candidate function
  inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:772:46: note: candidate function
  inline _LIBCPP_INLINE_VISIBILITY long double acos(long double __lcpp_x) _NOEXCEPT {return ::acosl(__lcpp_x);}
                                               ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fastcluster
Failed to build fastcluster
ERROR: Could not build wheels for fastcluster, which is required to install pyproject.toml-based projects


Is there a way to skip building fastcluster as it seems the problem is on this package? I already tried several possible fixes but none have worked and I still can't install astir. I am using Python 3.8 on macOS.
Thank you!

**Comment by joaoufrj** [comment]
Hi @kieranrcampbell I am struggling to install astir using Python 3.8. I have tried "pip install astir'' and "python setup.py install" and several other fixes but I continue to be hitting the wall and not being able to install the package AT ALL. It seems that there is an error when it tries to install and build fastcluster, as you can see below:
Building wheels for collected packages: fastcluster
  Building wheel for fastcluster (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/joaoluizsfilho/miniconda3/bin/python /Users/joaoluizsfilho/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/rl/ypn8k8pn6sn46890b2gh46040000gn/T/tmpvaburexf
       cwd: /private/var/folders/rl/ypn8k8pn6sn46890b2gh46040000gn/T/pip-install-5_q4u350/fastcluster_a41fe586050c4e7e83c8ecf111b6e457
  Complete output (107 lines):
  Fastcluster version: 1.2.4
  Python version: 3.8.5 (default, Sep  4 2020, 02:22:02)
  [Clang 10.0.0 ]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  copying fastcluster.py -> build/lib.macosx-10.9-x86_64-3.8
  running build_ext
  building '_fastcluster' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/src
  x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/joaoluizsfilho/miniconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/joaoluizsfilho/miniconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/joaoluizsfilho/miniconda3/include -I/private/var/folders/rl/ypn8k8pn6sn46890b2gh46040000gn/T/pip-build-env-34n2edic/overlay/lib/python3.8/site-packages/numpy/core/include -I/Users/joaoluizsfilho/miniconda3/include/python3.8 -c src/fastcluster_python.cpp -o build/temp.macosx-10.9-x86_64-3.8/src/fastcluster_python.o
  clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
  In file included from src/fastcluster_python.cpp:28:
  /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:14:2: error: "Something's broken.  UCHAR_MAX should be defined in limits.h."
  #error "Something's broken.  UCHAR_MAX should be defined in limits.h."
   ^
  /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:18:2: error: "Python's source code assumes C's unsigned char is an 8-bit type."
  #error "Python's source code assumes C's unsigned char is an 8-bit type."
   ^
  /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:27:5: error: "Python.h requires that stdio.h define NULL."
  #   error "Python.h requires that stdio.h define NULL."
      ^
  In file included from src/fastcluster_python.cpp:28:
  In file included from /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:30:
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:73:64: error: use of undeclared identifier 'strchr'
  char* __libcpp_strchr(const char* __s, int __c) {return (char*)strchr(__s, __c);}
                                                                 ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:80:75: error: use of undeclared identifier 'strpbrk'
  char* __libcpp_strpbrk(const char* __s1, const char* __s2) {return (char*)strpbrk(__s1, __s2);}
                                                                            ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:87:65: error: use of undeclared identifier 'strrchr'; did you mean 'strchr'?
  char* __libcpp_strrchr(const char* __s, int __c) {return (char*)strrchr(__s, __c);}
                                                                  ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:75:13: note: 'strchr' declared here
  const char* strchr(const char* __s, int __c) {return __libcpp_strchr(__s, __c);}
              ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:94:49: error: unknown type name 'size_t'
  void* __libcpp_memchr(const void* __s, int __c, size_t __n) {return (void*)memchr(__s, __c, __n);}
                                                  ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:96:46: error: unknown type name 'size_t'
  const void* memchr(const void* __s, int __c, size_t __n) {return __libcpp_memchr(__s, __c, __n);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:98:46: error: unknown type name 'size_t'
        void* memchr(      void* __s, int __c, size_t __n) {return __libcpp_memchr(__s, __c, __n);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:101:74: error: use of undeclared identifier 'strstr'; did you mean 'strchr'?
  char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                           ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:77:13: note: 'strchr' declared here
        char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
              ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:101:74: error: no matching function for call to 'strchr'
  char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                           ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:77:13: note: candidate disabled: <no message provided>
        char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
              ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:101:81: error: cannot initialize a parameter of type 'char *' with an lvalue of type 'const char *'
  char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                                  ^~~~
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/string.h:77:32: note: passing argument to parameter '__s' here
        char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
                                 ^
  In file included from src/fastcluster_python.cpp:28:
  In file included from /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:34:
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/stdlib.h:142:34: error: unknown type name 'ldiv_t'
  inline _LIBCPP_INLINE_VISIBILITY ldiv_t div(long __x, long __y) _NOEXCEPT {
                                   ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/stdlib.h:143:12: error: no member named 'ldiv' in the global namespace
    return ::ldiv(__x, __y);
           ~~^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/stdlib.h:146:34: error: unknown type name 'lldiv_t'
  inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x,
                                   ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/stdlib.h:148:12: error: no member named 'lldiv' in the global namespace
    return ::lldiv(__x, __y);
           ~~^
  In file included from src/fastcluster_python.cpp:28:
  In file included from /Users/joaoluizsfilho/miniconda3/include/python3.8/Python.h:63:
  In file included from /Users/joaoluizsfilho/miniconda3/include/python3.8/pyport.h:212:
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:771:93: error: no member named 'acosf' in the global namespace; did you mean 'acos'?
  inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                                                                            ~~^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:771:46: note: 'acos' declared here
  inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:772:93: error: no member named 'acosl' in the global namespace; did you mean 'acos'?
  inline _LIBCPP_INLINE_VISIBILITY long double acos(long double __lcpp_x) _NOEXCEPT {return ::acosl(__lcpp_x);}
                                                                                            ~~^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:771:46: note: 'acos' declared here
  inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:778:38: error: call to 'acos' is ambiguous
  acos(_A1 __lcpp_x) _NOEXCEPT {return ::acos((double)__lcpp_x);}
                                       ^~~~~~
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:771:46: note: candidate function
  inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                               ^
  /Users/joaoluizsfilho/miniconda3/bin/../include/c++/v1/math.h:772:46: note: candidate function
  inline _LIBCPP_INLINE_VISIBILITY long double acos(long double __lcpp_x) _NOEXCEPT {return ::acosl(__lcpp_x);}
                                               ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fastcluster
Failed to build fastcluster
ERROR: Could not build wheels for fastcluster, which is required to install pyproject.toml-based projects

I have tried several fixes to try to skip this error or install fastcluster but nothing has worked. Could you please give some help with this? I am trying to use astir as a step in the Squidpy/Scanpy pipeline and would be great if I could get this working.
Thank you!
Joao
